apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-lab 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts 
    targetRevision: 19.6.1
    chart: prometheus
    helm:
      values: |
        persistentVolume:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
