apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-lab
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision:  9.3.6
    helm:
      releaseName: grafana-lab 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
