apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.50.7
    chart: grafana
    helm:
      values: |
        adminPassword: strongpassword
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
