apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-lab
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision:  8.2.26
    helm:
      releaseName: grafana-lab 
      values: |
        persistence:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
