apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-lab
  namespace: argocd
spec:
  project: default
  source:
    chart: gitlab 
    repoURL: http://charts.gitlab.io/ 
    targetRevision: 6.8.3
    # helm:
    #   values: |
    #     persistence:
    #       enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab 
